package com.holy.sboot.origin.entity;

import com.holy.sboot.origin.basic.BaseEty;

/**
 * Model class of 权限表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Auth extends BaseEty<Auth> {

	private static final long serialVersionUID = 1L;

	// ID
	private Long id;
	// 权限编号
	private String authCode;
	// 权限名称
	private String authName;
	// 父级id
	private Long parentId;
	// 所有父级id
	private Long parentIds;
	// 排序
	private Integer sort;
	// 请求uri
	private String uri;
	// 权限标识
	private String permission;
	// 资源类型
	private String resourceType;
	// 描述
	private String description;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAuthCode() {
		return authCode;
	}

	public void setAuthCode(String authCode) {
		this.authCode = authCode;
	}

	public String getAuthName() {
		return authName;
	}

	public void setAuthName(String authName) {
		this.authName = authName;
	}

	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Long getParentIds() {
		return parentIds;
	}

	public void setParentIds(Long parentIds) {
		this.parentIds = parentIds;
	}

	public Integer getSort() {
		return sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getUri() {
		return uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public String getPermission() {
		return permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	public String getResourceType() {
		return resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
