package com.holy.sboot.origin.entity;

import java.util.ArrayList;
import java.util.List;

import com.holy.sboot.origin.basic.BaseEty;

/**
 * Model class of 角色表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Role extends BaseEty<Role> {

	private static final long serialVersionUID = 1L;

	// ID
	private Long id;
	// 角色编号
	private String roleCode;
	// 角色名称
	private String roleName;
	// 英文名称
	private String roleEName;
	// 数据范围
	private Integer dataScope;
	// 描述
	private String description;

	// 根据用户查询角色
	private User user;
	// 角色下的用户列表
	private List<User> userList = new ArrayList<>();
	// 角色对应的权限列表
	private List<Auth> authList = new ArrayList<>();

	public static final Integer DATA_SCOPE_ALL = 0;
	public static final Integer DATA_SCOPE_ROLE_AND_CHILD = 1;
	public static final Integer DATA_SCOPE_ROLE = 2;
	public static final Integer DATA_SCOPE_SELF = 3;
	public static final Integer DATA_SCOPE_CUSTOM = 4;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRoleCode() {
		return roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleEName() {
		return roleEName;
	}

	public void setRoleEName(String roleEName) {
		this.roleEName = roleEName;
	}

	public Integer getDataScope() {
		return dataScope;
	}

	public void setDataScope(Integer dataScope) {
		this.dataScope = dataScope;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public List<User> getUserList() {
		return userList;
	}

	public void setUserList(List<User> userList) {
		this.userList = userList;
	}

	public List<Auth> getAuthList() {
		return authList;
	}

	public void setAuthList(List<Auth> authList) {
		this.authList = authList;
	}

	public List<Long> getAuthIdList() {
		List<Long> authIdList = new ArrayList<>();
		for (Auth auth : authList) {
			authIdList.add(auth.getId());
		}
		return authIdList;
	}

	public void setAuthIdList(List<Long> authIdList) {
		authList = new ArrayList<>();
		for (Long authId : authIdList) {
			Auth auth = new Auth();
			auth.setId(authId);
			authList.add(auth);
		}
	}
}
