package com.holy.sboot.origin.entity;

import java.util.ArrayList;
import java.util.List;

import com.holy.sboot.origin.basic.BaseEty;

/**
 * Model class of 用户表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User extends BaseEty<User> {

	private static final long serialVersionUID = 1L;

	// ID
	private Long id;
	// 用户编号
	private String userCode;
	// 用户名
	private String userName;
	// 密码
	private String password;
	// 邮箱
	private String email;
	// 头像
	private String photo;
	// 手机
	private String mobile;
	// 描述
	private String description;

	// 根据角色查询用户
	private Role role;
	// 用户的角色列表
	private List<Role> roleList = new ArrayList<>();

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserCode() {
		return userCode;
	}

	public void setUserCode(String userCode) {
		this.userCode = userCode;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoto() {
		return photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public List<Role> getRoleList() {
		return roleList;
	}

	public void setRoleList(List<Role> roleList) {
		this.roleList = roleList;
	}
}
